version: 2.1

orbs:
  android: circleci/android@2.0

commands:
  save_test_results:
    description: "Saves all test results into a single directory"
    steps:
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

defaults: &defaults
  working_directory: ~/app
  executor:
    name: android/android-machine
    resource-class: large
    tag: 2021.10.1

jobs:
  version_build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "Generate build version"
          command: |
            ./gradlew setVersionBuild -Pversion=$CIRCLE_BUILD_NUM
            echo "Set build version to $CIRCLE_BUILD_NUM"
      - store_artifacts:
          path: "./app/gradle.properties"
          destination: gradle.properties
  android_lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "Static analysis"
          command: ./gradlew ktlint -PautoCorrect=0
  unit_tests:
    <<: *defaults
    steps:
      - checkout
      - android/run-tests:
          test-command: ./gradlew testDebug
      - save_test_results
      - android/save-gradle-cache
      - android/save-build-cache
  build_and_publish:
    <<: *defaults
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: "Assemble Feature Build"
          command: ./gradlew assembleFeature
      - store_artifacts:
          path: "./app/build/outputs/mapping/feature/mapping.txt"
          destination: artifact-file
      - run:
          name: "Distribute to Firebase App Distribution"
          command: ./gradlew appDistributionUploadFeature
      - store_artifacts:
          path: app/build/outputs/apk/feature
  commit:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "Commit gradle properties changes"
          command: |
            cat app/gradle.properties
            'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
            eval $(ssh-agent -s)
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
            git config user.name gitlab
            git config user.email gitlab@btsdigital.kz
            git remote set-url --push origin `echo $CI_REPOSITORY_URL | perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#'`
            git checkout -B ci_processing
            git commit -a -m "[CI SKIP] Bump version"
            git checkout $CI_COMMIT_REF_NAME
            git pull origin $CI_COMMIT_REF_NAME
            git checkout ci_processing
            git rebase -s recursive -X theirs $CI_COMMIT_REF_NAME
            git push origin ci_processing:$CI_COMMIT_REF_NAME
workflows:
  version: 2

  test_job:
    jobs:
      - version_build:
          context: feature
          filters:
            branches:
              only:
                - /(^feature\/.+)/
      - commit:
          filters:
            branches:
              only:
                - /(^feature\/.+)/

  lint_and_test:
    jobs:
      - android_lint:
          context: feature
          filters:
            branches:
              only:
                - /(^feature\/.+)/
      - unit_tests:
          requires:
            - android_lint
          context: feature
      - build_and_publish:
          requires:
            - unit_tests
          context: feature
          filters:
            branches:
              only:
                - merge_requests

  lint_test_and_publish_feature:
    jobs:
      - version_build:
          context: feature
          filters:
            branches:
              only:
                - master
                - develop
      - android_lint:
          requires:
            - version_build
          context: feature
      - unit_tests:
          requires:
            - android_lint
          context: feature
      - commit:
          requires:
            - unit_tests