# Simple CI config to upload APK to Firebase App Distribution
name: Android CI
on:
  push:
    branches:
      - develop
      - 'feature/**'

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run ktlint
        run: ./gradlew ktlint -PautoCorrect=0
  build:
    runs-on: ubuntu-latest
    needs: ktlint
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew assembleFeature
      - name: Upload APK to FirebaseAppDistribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: wallet.feature.test
          file: app/build/outputs/apk/feature/app-feature.apk